# Programming language definition
language: cpp

# Build matrix (OS, compiler)
matrix:
  include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
            - doxygen
            - graphviz
            - libbfd-dev
            - uuid-dev
    - os: linux
      compiler: clang
      env: CLANG_VERSION=3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - libc++-dev
            - libc++abi-dev
            - cmake
            - doxygen
            - graphviz
            - libbfd-dev
            - uuid-dev
    - os: osx
      compiler: clang
      osx_image: xcode8.2

# Using Trusty environment
sudo: required
dist: trusty

# Branches to build
branches:
  only:
    - master

# Clone depth
git:
  depth: 5

# Scripts that run before install
before_install:
  - cmake --version
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # gcc
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  # clang
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  # libc++
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then ls /usr/include/c++/v1; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then pushd .; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then popd; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then ls /usr/include/c++/v1; fi
  # libc++abi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then pushd .; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd libcxxabi/lib && bash buildit; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then sudo cp ./libc++abi.so.1.0 /usr/lib/; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then cd /usr/lib && sudo ln -sf libc++abi.so.1.0 libc++abi.so; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then sudo ln -sf libc++abi.so.1.0 libc++abi.so.1 && cd $cwd; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then popd; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$COMPILER" = "clang" ]; then ls /usr/include/c++/v1; fi
  # doxygen
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install doxygen; fi
  # graphviz
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install graphviz; fi

# Build scripts
script: 
  - cd build
  - ./unix.sh

# Don't send notifications on success
notifications:
  email:
    on_success: never
